<footer>
    <div>
        <div>
            <h4>info</h4>
        </div>
        <div>
            <h4>info</h4>
        </div>
        <div>
            <h4>info</h4>
        </div>
    </div>
</footer>